name: Genarate Keystore
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Quick Generate and Show
      run: |
        keytool -genkey -v -keystore release.jks -alias GnadGnaoh -keyalg RSA -keysize 2048 -validity 10000 -storetype JKS -storepass "Bin@2809" -keypass "Bin@2809" -dname "CN=NexAlloy, OU=Dev, O=NexAlloy, L=VN, S=VN, C=VN"
        echo "--- COPY CHUỖI DƯỚI ĐÂY VÀO KEYSTORE_BASE64 ---"
        base64 -w 0 release.jks
        echo -e "\n--------------------------------------------"
